'use client'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import {usePathname} from 'next/navigation'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const currentRoute = usePathname();
  const linkhref='className="rounded-lg px-3 py-2 text-slate-700 font-medium hover:bg-slate-100 hover:text-slate-900 ';
  const activeStyle = linkhref+' bg-white-400';
  const inactiveStyle = linkhref+'text-white';
  console.log(currentRoute)

  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className='h-[56px] flex justify-center items-center bg-orange-200 space-x-4'>
          <Link href='/' className={(currentRoute === '/')? activeStyle : inactiveStyle }>Home</Link>
          <Link href='/about'className={(currentRoute === '/about')? activeStyle : inactiveStyle } >About</Link>
          <Link href='/contact' className={(currentRoute === '/contact')? activeStyle : inactiveStyle }>Contact</Link>
        </nav>
        {children}</body>
    </html>
  )
}
